---
- name: Install HTTPD
  hosts: localhost
  become_user: madhu
  vars_files:
    - /etc/ansible/vars.yaml
  vars:
    ansible_become_pass: "{{ my_sudo_pass }}"
  tasks:
    - name: Install Apache HTTPD web server
      apt:
        name: apache2
        state: present
    - name: Start Apache HTTPD web server
      service:
        name: apache2
        state: started
