---
- name: Install HTTPD
  hosts: localhost
  become: yes
  remote_user: madhu
  vars_files:
    - /etc/ansible/vars.yaml
  vars:
    ansible_become_pass: "{{my_sudo_pass}}"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache HTTPD web server
      apt:
        name: apache2
        state: present

    - name: Start Apache HTTPD web server
      service:
        name: apache2
        state: started
